### ISSUE TITLE
Push background using convert

### ISSUE THREAD

**Issue by ivanarrizabalaga** [EyeSeeTea/malariapp#676]
The background service that pushes data to the server is still using our PushClient instead of using PushController (which relies on the sdk).

**Comment by idelcano** [comment]
So sorry to all.
@ifoche I can´t push in dev server: https://hnqis-dev.psi-mis.org/
I am having the response:
 D/TrackerDataSender: got this many events to send:1
 D/Retrofit: ---> HTTP PUT https://hnqis-dev.psi-mis.org/api/events/A2wdLJDiVs2
 D/RepoManager: Request{method=PUT, url=https://hnqis-dev.psi-mis.org/api/events/A2wdLJDiVs2, tag=Request{method=PUT, url=https://hnqis-dev.psi-mis.org/api/events/A2wdLJDiVs2, tag=null}}
 D/Retrofit: <--- HTTP 404 https://hnqis-dev.psi-mis.org/api/events/A2wdLJDiVs2 (555ms)
 D/RepoManager: there was an error..HTTP
 E/RepoManager: {"httpStatus":"Not Found","httpStatusCode":404,"status":"ERROR","message":"Event not found for uid: A2wdLJDiVs2"}

I tried in a branch(filter_monitor) before change the push and i have the same ERROR response. Is it a server problem?

I tried  to check in https://hnqis.psi-mis.org/ with ifoche user but i can´t pull the data( ifoche not have permissions now).

Adrian was solving the push problem (with the old way... ). And he solved it (the old push work). Is not working with dhis sdk now...

I do not want to bother him, but may need to be informed.

Its not important for this issue but my user idelcano is not logging(i using our user @ifoche).
I created this branch https://github.com/EyeSeeTea/malariapp/tree/fix_push_background

**Comment by adrianq** [comment]
@idelcano sorry, I forgot to mention. We have asked the system admin to delete  https://hnqis-dev.psi-mis.org/ and start from scratch again as they were not able to configure the server properly.They should be working on this at the moment. We will let you know when the server is up and running properly but for now please do not use this server for any kind of testing. Thanks for keeping us updated!

**Comment by idelcano** [comment]
ok! thanks you @adrianq   !

**Comment by ifoche** [comment]
@idelcano it seems that hnqis-dev work is done and server is operative. Can you please test your user and tell us if you're able to pull/push the server? My user seems to be ok

**Comment by idelcano** [comment]
@ifoche i tested in hnqis-dev and it still fails.
I tried in my fix_push branch, and in the last working branch(filter_monitor) before the push was changed.

The progressactionbar activity shows "Survey successfully pushed to dhis server", but the survey is not in the server, and the log is showing the same error:
D/TrackerDataSender: got this many events to send:1
D/Retrofit: ---> HTTP PUT https://hnqis-dev.psi-mis.org/api/events/ted5nbLyuif
D/RepoManager: Request{method=PUT, url=https://hnqis-dev.psi-mis.org/api/events/ted5nbLyuif, tag=Request{method=PUT, url=https://hnqis-dev.psi-mis.org/api/events/ted5nbLyuif, tag=null}}

 D/Retrofit: <--- HTTP 404 https://hnqis-dev.psi-mis.org/api/events/ted5nbLyuif (284ms)
D/RepoManager: there was an error..HTTP
E/RepoManager: {"httpStatus":"Not Found","httpStatusCode":404,"status":"ERROR","message":"Event not found for uid: ted5nbLyuif"}
D/.PushController: Updating pushed survey data...
D/.PushController: PUSH process...OK

**Comment by ifoche** [comment]
@idelcano I've created for you a user "idelcano" in hnqis-dev with same pass as ifoche, can you test it and tell me if everything's fine?

**Comment by idelcano** [comment]
@ifoche it not work.
I cant acces to
https://hnqis-dev.psi-mis.org/dhis-web-dashboard-integration/index.action
(or https://hnqis-dev.psi-mis.org/)
error:
Access denied

You don't have sufficient authority to view this page

And the pull fails too:

01-10 12:53:43.163 3268-3339/org.eyeseetea.malariacare.hnqispull
E/.CompositeScoreBuilder: There is no option named 'COMPOSITE_SCORE' which
is a severe data error
01-10 12:53:43.163 3268-3339/org.eyeseetea.malariacare.hnqispull
E/.PullController: onLoadMetadataFinished: Attempt to invoke virtual method
'java.lang.String
org.hisp.dhis.android.sdk.persistence.models.Option.getCode()' on a null
object reference

2016-01-10 18:34 GMT+01:00 Ignacio Foche <notifications@github.com>:

**Comment by ifoche** [comment]
can you try again? (sorry for this)

**Comment by idelcano** [comment]
@ifoche it still failing in the pull(same error).
In the website i can look the pilot test facility 1 and 2 but empty( if i
click in a test facility i can look "No Records Found")
I dont look any graphic in the index of the website.

2016-01-10 19:12 GMT+01:00 Ignacio Foche <notifications@github.com>:

**Comment by ifoche** [comment]
@idelcano for the web side, are you using chrome in incognito mode? The pull side, let me check it a little bit more

**Comment by idelcano** [comment]
yes @ifoche but i join in tracket capture not in event capture, in event
capture i can look the metadata of the events.
but the pull had the same error:
D/.PullController: Converting SDK into APP data
01-10 13:22:25.041 3740-3814/org.eyeseetea.malariacare.hnqispull
E/.CompositeScoreBuilder: There is no option named 'COMPOSITE_SCORE' which
is a severe data error
01-10 13:22:25.041 3740-3814/org.eyeseetea.malariacare.hnqispull
E/.PullController: onLoadMetadataFinished: Attempt to invoke virtual method
'java.lang.String
org.hisp.dhis.android.sdk.persistence.models.Option.getCode()' on a null
object reference


2016-01-10 19:16 GMT+01:00 Ignacio del Cano Costa <ignaciodelcano@gmail.com>
:

**Comment by idelcano** [comment]
@ifoche i dont find the element  named COMPOSITE_SCORE in the Option table
Name column in the DB of dhis
Example in a before DB pulled days ago:

"COMPOSITE_SCORE"    "NULL"    "2016-01-08T19:46:43.470-05:00"
"2016-01-08T19:46:43.470-05:00"    "null"    "J5E0go8T9oV93"    "7"
"J5E0go8T9oV"    "93"


2016-01-10 19:26 GMT+01:00 Ignacio del Cano Costa <ignaciodelcano@gmail.com>
:

**Comment by ifoche** [comment]
you should be able now to pull, push and everything you may want (be careful, you're temporarily superuser, don't mess with the permissions and all that stuff :) )

**Comment by idelcano** [comment]
I can pull now. But i can´t push(same error):
The log:
D/.PushController: Starting PUSH process...
D/.PushController: Preparing survey for pushing...
D/.PushController: Converting APP survey into a SDK event
D/.ConvertToSDKVisitor: Creating event for survey (231) ...
D/.ConvertToSDKVisitor: Saving event
org.hisp.dhis.android.sdk.persistence.models.Event@396418d2
D/.ConvertToSDKVisitor: Registering scores...
I/.ScoreRegister: Register tab score: Focused Antenatal Care
E/SQLiteLog: (284) automatic index on Question(id_composite_score)
I/.ScoreRegister: Register composite score: 1
I/.ScoreRegister: Register composite score: 1.1
I/.ScoreRegister: Register composite score: 1.2
I/.ScoreRegister: Register composite score: 1.3
I/.ScoreRegister: Register composite score: 1.4
I/.ScoreRegister: Register composite score: 1.5
D/.ScoreRegister: getCompositeScore 1 -> [0.02, 1.0799996]
D/.ConvertToSDKVisitor: Creating datavalues from scores...
D/.ScoreRegister: getCompositeScore 1 -> [0.02, 1.0799996]
D/.ScoreRegister: getCompositeScore 1.1 -> [0.0, 0.0]
D/.ScoreRegister: getCompositeScore 1.2 -> [0.02, 0.44000006]
D/.ScoreRegister: getCompositeScore 1.3 -> [0.0, 0.21]
D/.ScoreRegister: getCompositeScore 1.4 -> [0.0, 0.25]
D/.ScoreRegister: getCompositeScore 1.5 -> [0.0, 0.17999999]
D/.ConvertToSDKVisitor: Creating datavalues from questions...
D/.ConvertToSDKVisitor: Creating datavalues from other stuff...
D/.ConvertToSDKVisitor: 1 surveys converted so far

D/.PushController: Pushing survey data to server...
D/DataValueController: sending local data
D/TrackerDataSender: got this many events to send:1
D/Retrofit: ---> HTTP PUT
https://hnqis-dev.psi-mis.org/api/events/TVnTDnC7dST
D/RepoManager: Request{method=PUT, url=
https://hnqis-dev.psi-mis.org/api/events/TVnTDnC7dST,
tag=Request{method=PUT, url=
https://hnqis-dev.psi-mis.org/api/events/TVnTDnC7dST, tag=null}}
D/Retrofit: <--- HTTP 404
https://hnqis-dev.psi-mis.org/api/events/TVnTDnC7dST (502ms)
D/RepoManager: there was an error..HTTP
E/RepoManager: {"httpStatus":"Not
Found","httpStatusCode":404,"status":"ERROR","message":"Event not found for
uid: TVnTDnC7dST"}
D/.PushController: Updating pushed survey data...
D/.PushController: PUSH process...OK

2016-01-10 23:24 GMT+01:00 Ignacio Foche <notifications@github.com>:

**Comment by ifoche** [comment]
Maybe you're pushing against a pair OrgUnit/Program that is not allowed? can you test with test facility 1/KE HNQIS IMCI filling in every compulsory question? (Just a question, did you pull again to clear your previously downloaded OrgUnits/Programs?)

**Comment by idelcano** [comment]
I was pulling always with test facility 1 and focused antenatal care
program.
But i tried with test facility 1/KE HNQIS IMCI answering all questions
and i get same error
{"httpStatus":"Not
Found","httpStatusCode":404,"status":"ERROR","message":"Event not found for
uid: Q4tl9gL72m4"}

2016-01-10 23:46 GMT+01:00 Ignacio Foche <notifications@github.com>:

**Comment by ifoche** [comment]
ok...I think we will have to wait for @josemp10 to discover where does this problem comes from. In the meanwhile, are you able to push with ifoche or do you have the same problem?

**Comment by idelcano** [comment]
@ifoche sorry for the delay.
ifoche user has the same problem.



2016-01-11 0:08 GMT+01:00 Ignacio Foche <notifications@github.com>:

**Comment by ifoche** [comment]
ok, so that's clearly a problem in the app side, don't you think? If we were able to push with ifoche yesterday but not today... How are you testing the push? Can you test for example with R13 and tell me if the problem's still there?

**Comment by idelcano** [comment]
Sorry @ifoche but i never push in the server with dhis, i only can push with the R13 method.
I cant push with dhis Pullcontroller.

I dont know where is the problem but i was testing the dhis push before my changes in the push.(and in this fix branch).

Yesterday i only can push with:
 PushResult(pushData(data));
And never works in dev for me with:
PushController.getInstance().push(PreferencesState.getInstance().getContext(), surveys); 

I don´t know if the fail is in the server or in the send of events from dhis api( im not sure how works) anyway i was testing with a version without my changes.

If it worked on the old server, should work on this, no?. But i never checked if the surveys was saving in the server with the PullController, or i don´t rememmber it..

Example of the response (With R13, user ifoche):
{"httpStatus":"OK","httpStatusCode":200,"status":"OK","message":"Import was successful.","response":{"responseType":"ImportSummaries","imported":8,"updated":0,"ignored":0,"importSummaries":[{"responseType":"ImportSummary","status":"SUCCESS","importCount":{"imported":8,"updated":0,"ignored":0,"deleted":0},"reference":"kAK3KYf339Q","href":"https:\/\/hnqis-dev.psi-mis.org\/api\/events\/kAK3KYf339Q"}]}}

**Comment by ifoche** [comment]
@idelcano . I'm not sure to have properly understood your last message. Could we meet tomorrow morning to chat about it? (or now if you're still awake). If it's tomorrow, please let me know when you start working so we can talk before you start

**Comment by ifoche** [comment]
ok, just to leave a trace of this. Pull/Push are both working with SDK 2.20 and with users ifoche and idelcano. @idelcano is working now to reintroduce SDK push in development branch (this is what this task was about). 

Temporarily, @idelcano is superuser, and @josemp10 will take a look to this next Tuesday to check why are at this moment users needing to be superusers to have the pull working. Apparently it has something to do with attributes, but we will wait for @josemp10 news.

**Comment by idelcano** [comment]
Ok i think i solved it.
But i comment the information here before do PR:

I look a diference in the push with the R13.
In actual version the events have the created date saved. In R13 is null.

This was changed in the commit 52e4b529a5b43f3f82e3ddcf6cd9251a9061cc49

If the event create date is null, the sdk do a diferent push (POST or PUT):


if(event.getCreated() == null) {
    postEvent(event, dhisApi);
} else {
    putEvent(event, dhisApi);
}


@POST("/"+ApiEndpointContainer.EVENTS+"/")
Response postEvent(@Body Event event);

@PUT("/"+ApiEndpointContainer.EVENTS+"/{eventUid}")
Response putEvent(@Path("eventUid") String eventUid, @Body Event event);

i moved the setCreatedDate to after push, the event is saving in the server
(with sdk post method, like in R13).



Anyway, the PUT should be work in the server side?

I did some refactor too after merge with development (resolve a bug with
workflow seting the alarm , and refactor some names).

2016-01-11 3:36 GMT+01:00 Ignacio Foche <notifications@github.com>:
